# Generated by Django 3.2.8 on 2021-10-27 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='', verbose_name='Photo de profil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Editeur',
                'verbose_name_plural': 'Editeur',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_text', tinymce.models.HTMLField(blank=True, default='Le Blog qui vous rassemble et qui vous ressemble', null=True, verbose_name='Texte de la banniere')),
                ('banner_picture', models.ImageField(upload_to='', verbose_name="L'image de la banniere")),
                ('title', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Titre de texte intro section')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Contenu intro section')),
            ],
            options={
                'verbose_name': 'Bannière',
                'verbose_name_plural': 'Bannières',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Nom de la categorie')),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('overview', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment_count', models.IntegerField(default=0)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('featured', models.BooleanField(default=False, verbose_name='Publié ?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.author', verbose_name='Editeur')),
                ('category', models.ManyToManyField(to='post.Category')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
