# Generated by Django 3.2.8 on 2021-10-27 21:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20211027_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default=' ', verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=tinymce.models.HTMLField(default=' ', verbose_name='Aperçu'),
        ),
    ]
