# Generated by Django 3.2.8 on 2021-10-28 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0009_auto_20211028_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postview',
            options={'verbose_name': 'Article vu', 'verbose_name_plural': 'Articles vus'},
        ),
        migrations.AlterField(
            model_name='postview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='article vu'),
        ),
        migrations.AlterField(
            model_name='postview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur ayant vu'),
        ),
    ]
