# Generated by Django 3.2.8 on 2021-10-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=80, verbose_name='Titre')),
                ('big_size_pic', models.ImageField(upload_to='', verbose_name='grande image')),
                ('small_size_pic', models.ImageField(upload_to='', verbose_name='petite image')),
            ],
            options={
                'verbose_name': 'Galerie',
                'verbose_name_plural': 'Galeries',
            },
        ),
    ]
